### ISSUE TITLE
app.module.ts

### ISSUE THREAD

**Issue by VZhyrytskiy** [akparaliev/AngularTrainingProject#1]
Теперь вы знаете, что если сервис зарегистрирован как
@Injectable({
  providedIn: 'root'
})
export class ProductsService {
то его уже не нужно добавлять в проайдеры
providers: [ ProductsService ],
  bootstrap: [AppComponent]
})
export class AppModule { }

**Comment by akparaliev** [comment]
https://github.com/akparaliev/AngularTrainingProject/commit/eed7337d5343b55142e12ace53a3edc0d0916e8d
