### ISSUE TITLE
demo.component.ts

### ISSUE THREAD

**Issue by VZhyrytskiy** [akparaliev/AngularTrainingProject#3]
Думаю, тут
 @Optional() public generatorService: GeneratorService,
должно быть по другому. У вас нет зарегистрированого сервиса GeneratorService. Есть токен Generator5, а значит внедрять надо с поощью @Inject(Generstor5)...

**Comment by akparaliev** [comment]
https://github.com/akparaliev/AngularTrainingProject/commit/a9a58679dfe162f4880347624444beb32e435b09
