### ISSUE TITLE
product-list.component.ts

### ISSUE THREAD

**Issue by VZhyrytskiy** [akparaliev/AngularTrainingProject#6]
ngAfterViewInit() {
    this.popularProduct = this.productChild.product.name;
  }
Это приводит ошибке
ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'null: undefined'. Current value: 'null: product1'.
Это из за того, что в родительском компоненте получаем доступ к дочернему, и устанавливаем свойство в родительском, а затем его в шаблон и снова по кругу.

**Comment by akparaliev** [comment]
https://github.com/akparaliev/AngularTrainingProject/commit/eb2fc9d9d24ee60a2c06aa2f5a347438fde1a0da
